- data -
  -iris: [sepal lenght, sepal witdh, species]
  -titanis [pclass, sibling, spouse, fare, age, gender, survival]
  -tips[]
  -penguins: [species, island, lenght, witdh]

Column = vectors

In [22]:
list2 = [3,4,5, 'idrees', 4.5, [3,['a','b'],5]]

list2[5][1][0]

'a'

In [45]:
vectorx = [3,4,[5,6,7],3]

vectorx[2][1]

6

In [46]:

vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

sum(vector1)
len(vector1) # number of element]

3

In [47]:

import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var() # 8.0
arr.std() # 2.82

np.float64(2.8284271247461903)

In [48]:

vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1, 
          vector2, 
          vector3] # 0 1 2

matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrix

# how to check the dimensions?

 # [2,4,10] as a result
 # 2 as a result

[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [52]:
matrix_arr = np.array([
    [1,2,3,4,5,6,7,8,9],
    [9,8,7,6,5,4,3,2,1],
    [3,3,3,3,3,3,3,3,3]
])

matrix_arr[0:2, 8]

# row  x  column

array([9, 1])

In [53]:
matrix_arr[0:2, 8]


array([9, 1])

In [54]:
matrix = [[10,4,10], # 0
          [20,4,10], # 1   # 0
          [30,4,10], # 2   # 1
          [30,4,10]] # 3

matrixarr = np.array(matrix)

In [67]:
matrixarr = np.array([
    [10, 4, 10],
    [20, 4, 10],
    [30, 4, 10],
    [30, 4, 10]
])

# Rows 1-2, column 2
print(matrixarr[1:3, 2])# rows 

[10 10]


In [69]:
#Access a single element
matrixarr[1, 2]  # output: 10


np.int64(10)

In [56]:
matrixarr[1][2]


np.int64(10)

In [57]:
matrixarr * 2 # scalar multiplication

# scaler operations with arrays
# 

matrixarr.ndim
matrixarr.shape # how many rows and columns

# rows  x  columns

(4, 3)

In [58]:

# broadcastinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110],
       [130, 104, 110]])

In [59]:

a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]]
             )
b = np.array([[10], 
              [100]])

a - b
a * b
a / b
a + b

array([[ 11,  13,  15,  16],
       [102, 108, 107, 109]])

In [60]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [61]:
((variance)**0.5) .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [62]:

covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22,  650.8])

stdx
stdy


r = covariance/(stdx*stdy)
r

array([0.58575649, 1.70715621])

In [63]:

x = np.array([[1,4,1],
              [2,5,2]])

w = np.array([10,10,10])

w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw = np.dot(x,w)
matmultiply_xw

array([60, 90])

In [64]:
matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [65]:
matmultiply_xw2 = x @ w2
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [66]:
matmultiply_xw2 = np.matmul(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [ ]:
A =
2 3 4 
6 7 8
3 2 3

shape = 3 x 3  2 x 3

B =
5 5 5
2 2 2

shape = 2 x 3

2 x 3 = 3 x 3

In [74]:
import numpy as np

# Matriks A 3x3
A = np.array([
    [2, 3, 4],
    [6, 7, 8],
    [3, 2, 3]
])

# Matriks B 2x3
B = np.array([
    [5, 5, 5],
    [2, 2, 2]
])

B @ A
# matrix multiplication is not commutative


array([[55, 60, 75],
       [22, 24, 30]])

In [73]:
#Darab matriks (matrix multiplication)
# Darab B dan A
C = np.dot(B, A)

print("B · A =")
print(C)

B · A =
[[55 60 75]
 [22 24 30]]


In [81]:
A = np.array([
    [5, 5, 5],
    [2, 2, 2],
    [5, 5, 5]
])

# Matriks B 2x3
B = np.array([
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3]
])

print ('Matrix Multiplication: \n',A @ B,'\n')
print('Array Multiplication: \n',A * B)

Matrix Multiplication: 
 [[45 45 45]
 [18 18 18]
 [45 45 45]] 

Array Multiplication: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]


# Lists are built-in Python type.
# no need to import anything.
# Can store any type of data: integers, floats, strings, even other lists.
# Flexible, but slower for heavy numerical computations.

In [ ]:
#List Example
#lst = [1, 2, 3, "hello", [4,5]]


# NumPy arrays are part of the NumPy library, specifically for numerical operations.
# Comes from the NumPy library (import numpy as np).
# Designed for numerical computations.
# All elements must be the same type (homogeneous).
# Much faster than lists for math operations, and supports multi-dimensional arrays.

In [ ]:
#numpy Example
#import numpy as np

#arr = np.array([1, 2, 3])
#arr2d = np.array([[1,2,3], [4,5,6]])
